# Generated by Django 2.2.1 on 2019-05-27 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateslot',
            unique_together={('date', 'interview')},
        ),
        migrations.AlterUniqueTogether(
            name='interviewerslot',
            unique_together={('date', 'interview', 'user')},
        ),
    ]
